name: alunos
description: Exemplo de uso de command line no dart.
version: 1.0.0
homepage: https://github.com/tommymolto/dart-basics

environment:
  sdk: '>=2.18.6 <3.0.0'

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
dependencies:
  io: ^1.0.3
